/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Assignment;
import Business.Business;
import Business.Course;
import Business.CourseList;
import Business.Profiles.FacultyProfile;
import Business.Profiles.StudentProfile;
import Business.StudentCourseAssignmentBean;
import Business.StudentCourseBean;
import ManagerBean.CourseManagerBean;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manal
 */
public class StudentCourseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * C
     * reates new form StudentCourseWork
     */
    Business business;

    JPanel CardSequencePanel;
    Course course;
    StudentProfile profile;
    CourseManagerBean courseManagerBean;

    public StudentCourseWorkAreaJPanel(Business business, StudentProfile profile, CourseManagerBean courseManagerBean, Course course, JPanel CardSequencePanel) {
        initComponents();

        this.business = business;
        this.courseManagerBean = courseManagerBean;
        this.CardSequencePanel = CardSequencePanel;
        this.course = course;
        this.profile = profile;
        displayAssignmentWork();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtAssignmentSubmitLink = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSubmitAssignment = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Assignment ", "Submission Date", "Status", "Marks(Out of 100)"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtAssignmentSubmitLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssignmentSubmitLinkActionPerformed(evt);
            }
        });

        jLabel1.setText("Please post your github link");

        btnSubmitAssignment.setText("Submit Assignment");
        btnSubmitAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAssignmentActionPerformed(evt);
            }
        });

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(txtAssignmentSubmitLink, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmitAssignment))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(439, 439, 439)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAssignmentSubmitLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmitAssignment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAssignmentSubmitLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssignmentSubmitLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssignmentSubmitLinkActionPerformed

    private void btnSubmitAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAssignmentActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable1.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Assignment selectedAssignment = (Assignment) model.getValueAt(selectedRowIndex, 0);

        String assignmentSubmitLink = txtAssignmentSubmitLink.getText();
        if (assignmentSubmitLink.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please add submission link");
        } else {
            StudentCourseAssignmentBean.initialize();
            selectedAssignment.addSubmissionLink(profile, assignmentSubmitLink);

            StudentCourseAssignmentBean.saveStudentCourseAssignment(profile, course, selectedAssignment);
            JOptionPane.showMessageDialog(this, "Assignment Submitted Sucessfully");

            System.out.println("*******" + selectedAssignment.getSubmissionLinkStudent(profile));

            displayAssignmentWork();
        }
    }//GEN-LAST:event_btnSubmitAssignmentActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnSubmitAssignment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAssignmentSubmitLink;
    // End of variables declaration//GEN-END:variables

    private void displayAssignmentWork() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Assignment assignment : courseManagerBean.findAssignmentByCourse(course)) {
            //  List<Course> studentCourses = StudentCourseBean.studentCourseMap.get(student);

            Object[] row = new Object[3];
            row[0] = assignment;

            row[1] = assignment.getSubmissionDate();

            // row[2] = assignment.getStatus();
            row[2] = assignment.getMarksObtained();
            model.addRow(row);
        }

    }
}
