/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Course;
import Business.CourseList;
import Business.Profiles.FacultyProfile;
import Business.Profiles.StudentProfile;
import Business.StudentCourseBean;
import Business.UserAccounts.UserAccount;
import ManagerBean.CourseManagerBean;
import ManagerBean.FacultyManagerBean;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.AdministerPersonJPanel;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manal
 */
public class StudentCourseWorkJPanel extends javax.swing.JPanel {

    Business business;
    StudentProfile student;
    CourseList courselists;
    CourseManagerBean courseManagerBean;
    String selectedCourse = null;
    String selectedProfessor = null;
    FacultyManagerBean facultyManagerBean;
    JPanel CardSequencePanel;
    Course selectedCorse;
    
    
    public StudentCourseWorkJPanel() {
        initComponents();
    }

    public StudentCourseWorkJPanel(Business business, StudentProfile student, CourseList courselist, CourseManagerBean courseManagerBean, FacultyManagerBean facultyManagerBean,JPanel CardSequencePanel) {
        this.business = business;
        this.student = student;
        this.courselists = courselists;
        this.courseManagerBean = courseManagerBean;
        this.CardSequencePanel =CardSequencePanel ;
        initComponents();
        populateTable();
    }

    private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

         List<Course> studentCourses = StudentCourseBean.studentCourseMap.get(student);
         System.out.println("UserInterface.WorkAreas.StudentRole.StudentCourseWorkJPanel.populateTable()" + student.getPerson().getId());
         if(studentCourses!=null){
        for (Course course : studentCourses) {
            Object[] row = new Object[3];
            row[0] = course;

            FacultyProfile faculty = StudentCourseBean.courseFacultyMap.get(course);
            if(faculty!=null)
            row[1] = faculty.getPerson().getId();

            row[2] = "9am-10am";
            model.addRow(row);
        }
    
         }else
         {
             JOptionPane.showMessageDialog(this, "Please register course first");
         }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        Next = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Faculty Name", "Timings"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnBack.setText("Back >>");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        Next.setText("Next >>");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(495, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Next))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //
    }//GEN-LAST:event_btnBackActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
         if(selectedCorse==null) return;
        
          StudentCourseWorkAreaJPanel scwap = new StudentCourseWorkAreaJPanel(business,student,courseManagerBean,selectedCorse,CardSequencePanel);
        CardSequencePanel.add(scwap);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        
    }//GEN-LAST:event_NextActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        
         int size = jTable1.getRowCount();
        int selectedrow = jTable1.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selectedCorse = (Course) jTable1.getValueAt(selectedrow, 0);
        if (selectedCorse == null) {
            return;
        
        }
    }//GEN-LAST:event_jTable1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
