/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.ManageCourses;

import Business.Course;
import Business.CourseList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrey
 */

public class ViewCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCoursesJPanel
     */
    CourseList courselist;
        JPanel CardSequencePanel;
    public ViewCoursesJPanel( CourseList courselist,JPanel jp) {
        this.CardSequencePanel = jp;
        this.courselist = courselist;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CourseJTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCourseCredit = new javax.swing.JLabel();
        lblCourseDepartment = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtCourseCredit = new javax.swing.JTextField();
        txtCourseCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCourseDepartment = new javax.swing.JList<>();

        CourseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Name", "Course Code", "Course  Credit", "Course Dpartment"
            }
        ));
        jScrollPane1.setViewportView(CourseJTable);

        jButton1.setText("Back <");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Course Code:");

        jLabel2.setText("Course Name:");

        lblCourseCredit.setText("Course Credit:");

        lblCourseDepartment.setText("Course Department: ");

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtCourseDepartment.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Civil Engineering", "Information System", "Mechnical Engineering", "Electronic Engineering ", "Chemical Engineering " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        txtCourseDepartment.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(txtCourseDepartment);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(127, 127, 127))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(131, 131, 131)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblCourseCredit)
                                            .addComponent(lblCourseDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(92, 92, 92)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCourseCredit, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCourseName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCourseCode, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseCredit)
                    .addComponent(txtCourseCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseDepartment)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
 //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = CourseJTable.getSelectedRow();
      
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            
            return;
        }
      
        DefaultListModel<String> departmentListModel = new DefaultListModel<>();
        JList<String> txtCourseDepartment = new JList<>(departmentListModel);

        txtCourseDepartment.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        DefaultTableModel model = (DefaultTableModel)CourseJTable.getModel();
        Course selectedCourse = (Course)model.getValueAt(selectedRowIndex,0);
        
        String department = selectedCourse.getDepartment(); // Assuming this method returns the department as a String
        System.out.println("department"+department);
        departmentListModel.clear(); // Clear the previous data in the list
        departmentListModel.addElement(selectedCourse.getDepartment()); // Add the new department


        int selectedIndex = departmentListModel.indexOf(department);
        System.out.println("selectedIndex"+selectedIndex);
        
        txtCourseName.setText(selectedCourse.getCourseName());
        txtCourseCode.setText(selectedCourse.getCourseCode());
        txtCourseCredit.setText(String.valueOf(selectedCourse.getCredit()));
        if (selectedIndex >=0) {
           txtCourseDepartment.setSelectedIndex(selectedIndex);
        }
        txtCourseDepartment.updateUI();
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = CourseJTable.getSelectedRow();
        
        
        if( selectedRow < 0 ){
                JOptionPane.showMessageDialog(jScrollPane1, "Please select a row to update","Warning",JOptionPane.WARNING_MESSAGE);
        
        }else{
             DefaultTableModel model = (DefaultTableModel)CourseJTable.getModel();
             Course selectedCourse = (Course)model.getValueAt(selectedRow,0);
             
             String courseName = txtCourseName.getText();
             String courseCode = txtCourseCode.getText();
             Integer courseCredit = Integer.valueOf(txtCourseCredit.getText());
             String courseDepartment = txtCourseDepartment.getSelectedValue();
 
             
             
             selectedCourse.setCourseCode(courseCode);
             selectedCourse.setCourseName(courseName);
             selectedCourse.setCredit(courseCredit);
             selectedCourse.setDepartment(courseDepartment);
            
        }
        populateTable();
        JOptionPane.showMessageDialog(null, "Course updated successfully");
    }//GEN-LAST:event_jButton3ActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CourseJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseCredit;
    private javax.swing.JLabel lblCourseDepartment;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtCourseCredit;
    private javax.swing.JList<String> txtCourseDepartment;
    private javax.swing.JTextField txtCourseName;
    // End of variables declaration//GEN-END:variables
 private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) CourseJTable.getModel();
        dtm.setRowCount(0);
        for(Course course : courselist.getCourseList()){
            Object[] row = new Object[4];
            row[0]=course;
            row[1]= course.getCourseCode();
            row[2] = course.getCredit();
            row[3] = course.getDepartment();
            
            dtm.addRow(row);
        }
    }

}
